######################################################################
# Automatically generated by qmake (3.0) Sat Mar 7 03:15:10 2020
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../libsimpleT9/inc

QT += gui widgets

# Input
SOURCES += test.cpp

HEADERS += 

CONFIG += C++11 debug warn_on 

LIBS += -L../libsimpleT9 -lsimpleT9

OBJECTS_DIR = .obj
MOC_DIR = .obj

QMAKE_CLEAN += test
