################################################################################
# 自动生成的文件. 不要进行编辑!
################################################################################


CROSS_PREFIX := gnumips

CONFIG_COMPLILE_FLAGS += \
				-B"$(REDE_HOME)/user resource/loongson3a_7a1000_csp_config/runtimelib/LOONGSON3A_SMP/lib" -mabi=n32 -march=mips64r2 -mel -D_GS464_ -D__mips_abi_n32__ -D__multi_core__ -DCPU=MIPS64 -G0 -D__loongson2_64__ -DREWORKS_RTP -D__KERNEL__ \
				-B"$(REDE_HOME)/user resource/loongson3a_7a1000_bsp_config/runtimelib/LOONGSON3A_SMP/lib" -D_LOONGSON3A_780E_ -DUSE_REWORKS_IPNET_69 -D__WITH_GJ_PROTECT__ \
				-D__reworks__ \
				-D__reworks__

CPPFLAGS += \
				-I"$(REDE_HOME)/user resource/pci_config/runtimelib/h" \
				-I"$(REDE_HOME)/user resource/loongson3a_7a1000_bsp_config/runtimelib/LOONGSON3A_SMP/h" \
				-I"$(REDE_HOME)/user resource/io_config/runtimelib/h" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/freetype" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/freetype/config" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/iconv" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/jpeg" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/png" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/tiff" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refbsupport/zlib" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refb" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refb/direct" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refb/fusion" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/refb/fusion/shm" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/qt/QtGui" \
				-I"$(REDE_HOME)/user resource/ipnet_config/runtimelib/h" \
				-I"$(REDE_HOME)/resource/reworks_config/runtimelib/h" \
				-I"$(REDE_HOME)/resource/reworks_config/runtimelib/LOONGSON3A_SMP/h" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/qt/QtPlatformSupport" \
				-I"$(REDE_HOME)/user resource/vx_config/runtimelib/h" \
				-I"$(REDE_HOME)/user resource/loongson3a_7a1000_csp_config/runtimelib/h/mmu" \
				-I"$(REDE_HOME)/user resource/loongson3a_7a1000_csp_config/runtimelib/h/mmu/arch/mips/h" \
				-I"$(REDE_HOME)/user resource/loongson3a_7a1000_csp_config/runtimelib/h/mmu/h" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/qt" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/qt/QtCore" \
				-I"$(REDE_HOME)/user resource/graphics_config/runtimelib/h/qt/QtWidgets"

CONFIG_LD_FLAGS += \
				-B"$(REDE_HOME)/tools/build/gnumips/mipsel-elf/lib/mabi-n32/march-mips64r2/fast-math" \
				-B"$(REDE_HOME)/tools/build/gnumips/lib/gcc/mipsel-elf/4.8.4/mabi-n32/march-mips64r2/fast-math" \
				-B"$(REDE_HOME)/user resource/loongson3a_csp_config/runtimelib/LOONGSON3A_SMP/lib" -specs csp_specs -qrtos \
				-B"$(REDE_HOME)/user resource/loongson3a_7a1000_bsp_config/runtimelib/LOONGSON3A_SMP/lib"  -Wl,-Ttext,0x80200000

CONFIG_LINK_DYNAMIC_FLAGS += \
				--oformat=elf32-nlittlemips

LDFLAGS += \
				-L"$(REDE_HOME)/user resource/pci_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/loongson3a_7a1000_csp_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/graphics_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/loongson3a_7a1000_bsp_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/io_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/fs_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/ipnet_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/resource/reworks_config/runtimelib/LOONGSON3A_SMP/lib" \
				-L"$(REDE_HOME)/user resource/vx_config/runtimelib/LOONGSON3A_SMP/lib"

LIBS_CFG := -l"pci" -l"loongson3a_csp" -l"qtfreetype" -l"loongson3a_7a1000_bsp" -l"gpu" -l"gfxdriver" -l"io" -l"refbsupport" -l"refb" -l"Qt5Gui" -l"qtLink" -l"dosfs" -l"net" -l"reworks" -l"Qt5PlatformSupport" -l"vx" -l"mmu" -l"qdirectfb" -l"Qt5Core" -l"Qt5Concurrent" -l"Qt5Widgets" -l"qtpcre"

LD_OBJS = $(OBJS)