######################################################################
# Automatically generated by qmake (3.0) Sat Mar 7 03:15:10 2020
######################################################################

TEMPLATE = app
TARGET = ../simpleT9
INCLUDEPATH += . ../libsimpleT9/inc

QT += gui widgets

# Input
SOURCES += main.cpp

CONFIG += C++11 debug warn_on 

LIBS += -L../libsimpleT9 -lsimpleT9

OBJECTS_DIR = ../.obj
MOC_DIR = ../.obj

QMAKE_CLEAN += ../simpleT9 
